name: docs

on:
  push:
    branches: [ main ]           # rebuild on every push to main
  workflow_dispatch:             # manual trigger from the Actions tab

permissions:
  contents: write                # allow the workflow to push to gh‑pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout your source
    - uses: actions/checkout@v4

    # 2. Install Python
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # 3. Cache pip to speed up subsequent runs (optional)
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

    # 4. Install MkDocs & plugins
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 5. Build the site
    - name: Build site
      run: mkdocs build --strict

    # 6. Deploy to GitHub Pages (gh‑pages branch)
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4     # battle‑tested deploy action
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./site
